# Default values for Elastic Stack.
elasticsearch:
  resources:
    requests:
      memory: "1Gi"
      cpu: "100m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
kibana:
  enabled: true
logstash:
  enabled: true

