apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-engine
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: longhorn-engine
  template:
    metadata:
      labels:
        app: longhorn-engine
    spec:
      containers:
        - name: engine
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
