apiVersion: v1
kind: Service
metadata:
  name: longhorn-ui
  labels:
    app: longhorn-ui
spec:
  selector:
    app: longhorn-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
