# Steps to install RKE2
---

- name: Install RKE2 on master node
  ansible.builtin.shell: |
    curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=server sh -
  when: inventory_hostname == 'master1'
  become: yes
  notify:
    - Restart rke2-server

- name: Ensure RKE2 server is enabled and running
  ansible.builtin.systemd:
    name: rke2-server
    enabled: yes
    state: started
  when: inventory_hostname == 'master1'
  become: yes

- name: Wait for RKE2 server to become ready
  ansible.builtin.wait_for:
    path: /var/lib/rancher/rke2/server/node-token
    state: present
  when: inventory_hostname == 'master1'
  become: yes
  retries: 5
  delay: 10

- name: Check if kubectl symbolic link already exists
  ansible.builtin.stat:
    path: /usr/local/bin/kubectl
  register: kubectl_link

- name: Find kubectl binary path
  ansible.builtin.shell: find /var/lib/rancher/rke2/data/ -name kubectl | head -n 1
  register: kubectl_binary_path
  when: not kubectl_link.stat.exists

- name: Create symbolic link for kubectl
  ansible.builtin.shell: ln -s {{ kubectl_binary_path.stdout }} /usr/local/bin/kubectl
  when: not kubectl_link.stat.exists and kubectl_binary_path.stdout != ''
  become: yes

- name: Set KUBECONFIG environment variable globally
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: 'KUBECONFIG="/etc/rancher/rke2/rke2.yaml"'
    create: yes
  become: yes

- name: Ensure RKE2 directory exists on worker nodes
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    mode: '0755'
  become: yes
  when: inventory_hostname in ['worker1', 'worker2']

- name: Check if RKE2 server is running
  ansible.builtin.command: systemctl is-active rke2-server
  register: rke2_server_status
  failed_when: rke2_server_status.stdout != "active"
  become: yes
  when: inventory_hostname == 'master1'
  retries: 5
  delay: 10
  until: rke2_server_status.stdout == "active"

- name: Fetch RKE2 node token from master
  ansible.builtin.slurp:
    src: /var/lib/rancher/rke2/server/node-token
  register: rke2_node_token
  when: inventory_hostname == 'master1'
  become: yes
  run_once: true

- name: Install RKE2 on worker nodes
  ansible.builtin.shell: |
    curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE='agent' sh -
  when: inventory_hostname in ['worker1', 'worker2']
  become: yes
  notify:
    - Restart rke2-agent

- name: Set up RKE2 agent environment file on worker nodes
  ansible.builtin.template:
    src: templates/rke2_agent_config.j2
    dest: /etc/rancher/rke2/config.yaml
  vars:
    master_ip: "{{ hostvars['master1'].ansible_host }}"
    master_token: "{{ rke2_node_token.content | b64decode }}"
  when: inventory_hostname in ['worker1', 'worker2']
  become: yes

- name: Ensure RKE2 agent is enabled and running
  ansible.builtin.systemd:
    name: rke2-agent
    enabled: yes
    state: started
  when: inventory_hostname in ['worker1', 'worker2']
  become: yes
