# Steps to File Transfer
---

- name: Ensure RKE2 server is enabled and running
  ansible.builtin.systemd:
    name: rke2-server
    enabled: true
    state: started
  when: inventory_hostname == 'master1'

- name: Find home directory for UID 1000
  command: getent passwd 1000
  register: getent_passwd_output
  changed_when: false
  when: inventory_hostname == 'master1'

- name: Set home directory variable
  set_fact:
    user_home_directory: "{{ getent_passwd_output.stdout.split(':')[5] }}"
  when: inventory_hostname == 'master1' and getent_passwd_output.stdout != ""

- name: Copy config directory to user's home directory
  copy:
    src: ./my-charts/
    dest: "{{ user_home_directory }}/my-chats/"
    owner: 1000
    group: 1000
    mode: '0755'
  when: inventory_hostname == 'master1' and user_home_directory is defined
