# Steps to install MetalLB
---

    - name: MetalLB için hedef dizinin oluşturulması
      ansible.builtin.file:
        path: /etc/kubernetes/metalLB
        state: directory
        mode: '0755'
      when: inventory_hostname == 'master1'

    - name: metallb-config.yaml dosyasının kopyalanması
      ansible.builtin.copy:
        src: metallb/metallb-config.yaml
        dest: /etc/kubernetes/metalLB/metallb-config.yaml
        mode: '0644'
      when: inventory_hostname == 'master1'

    - name: metallb.yaml dosyasının kopyalanması
      ansible.builtin.copy:
        src: metallb/metallb.yaml
        dest: /etc/kubernetes/metalLB/metallb.yaml
        mode: '0644'
      when: inventory_hostname == 'master1'

    - name: MetalLB Namespace'inin Kontrolü
      ansible.builtin.command:
        cmd: kubectl get ns metallb-system
      register: ns_check
      ignore_errors: yes
      when: inventory_hostname == 'master1'

    - name: metallb.yaml'ın uygulanması (Eğer MetalLB Namespace'i yoksa)
      ansible.builtin.command:
        cmd: kubectl apply -f /etc/kubernetes/metalLB/metallb.yaml
      when: ns_check.rc != 0 and inventory_hostname == 'master1'

    - name: metallb-config.yaml'ın uygulanması
      ansible.builtin.command:
        cmd: kubectl apply -f /etc/kubernetes/metalLB/metallb-config.yaml
      when: inventory_hostname == 'master1'
