# Steps to install NGINX Ingress
---

- name: Add NGINX Ingress Helm repository
  community.kubernetes.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx
  when: inventory_hostname == 'master1'

- name: Update Helm repository list
  ansible.builtin.command:
    cmd: helm repo update
  when: inventory_hostname == 'master1'

- name: Install Longhorn Helm chart
  ansible.builtin.command:
    cmd: helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace -f {{ user_home_directory }}/my-charts/ingress/values.yaml
  when: inventory_hostname == 'master1'
