# Steps to install Metallb
---
- name: Add MetalLB Helm repository
  ansible.builtin.command:
    cmd: helm repo add metallb https://metallb.github.io/metallb
  when: inventory_hostname == 'master1'

- name: Update Helm repository list
  ansible.builtin.command:
    cmd: helm repo update
  when: inventory_hostname == 'master1'

- name: Install MetalLB Helm chart
  ansible.builtin.command:
    cmd: helm install metallb metallb/metallb --namespace metallb-system --create-namespace -f {{ user_home_directory }}/my-charts/metallb/values.yaml
  when: inventory_hostname == 'master1'
