# Steps to install Metallb & Longhorn
---

- name: Find home directory for UID 1000
  command: getent passwd 1000
  register: getent_passwd_output
  changed_when: false
  when: inventory_hostname == 'master1'

- name: Set home directory variable
  set_fact:
    user_home_directory: "{{ getent_passwd_output.stdout.split(':')[5] }}"
  when: inventory_hostname == 'master1' and getent_passwd_output.stdout != ''

- name: Download MetalLB manifest
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/metallb/metallb/v0.14.4/config/manifests/metallb-native.yaml
    dest: "{{ user_home_directory }}/config/metallb.yaml"
  when: inventory_hostname == 'master1'

- name: Apply MetalLB manifest
  ansible.builtin.command:
    cmd: kubectl apply -f {{ user_home_directory }}/config/metallb.yaml
  when: inventory_hostname == 'master1'

- name: Apply custom MetalLB ConfigMap
  ansible.builtin.command:
    cmd: kubectl apply -f {{ user_home_directory }}/config/metallb-config.yaml
  when: inventory_hostname == 'master1'

- name: Add Longhorn Helm repository
  ansible.builtin.command:
    cmd: helm repo add longhorn https://charts.longhorn.io
  when: inventory_hostname == 'master1'

- name: Update Helm repository list
  ansible.builtin.command:
    cmd: helm repo update
  when: inventory_hostname == 'master1'

- name: Install Longhorn Helm chart
  ansible.builtin.command:
    cmd: helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace -f {{ user_home_directory }}/config/longhorn-config.yaml
  when: inventory_hostname == 'master1'

- name: Apply Longhorn UI Service definition
  ansible.builtin.command:
    cmd: kubectl apply -f {{ user_home_directory }}/config/longhorn-ui-service.yaml
  when: inventory_hostname == 'master1'
