# Steps to install Metallb
---

- name: Install MetalLB
  ansible.builtin.command:
    cmd: kubectl apply -f {{ user_home_directory }}/my-charts/metallb/metallb.yaml
  when: inventory_hostname == 'master1'

- name: Apply MetalLB ConfigMap
  ansible.builtin.shell:
    cmd: kubectl apply -f {{ user_home_directory }}/my-charts/metallb/metallb-config.yaml
  when: inventory_hostname == 'master1'
