# Steps to install Longhorn
---

- name: Find home directory for UID 1000
  command: getent passwd 1000
  register: getent_passwd_output
  changed_when: false
  when: inventory_hostname == 'master1'

- name: Set home directory variable
  set_fact:
    user_home_directory: "{{ getent_passwd_output.stdout.split(':')[5] }}"
  when: inventory_hostname == 'master1' and getent_passwd_output.stdout != ''

- name: Add Longhorn Helm repository
  ansible.builtin.command:
    cmd: helm repo add longhorn https://charts.longhorn.io
  when: inventory_hostname == 'master1'

- name: Update Helm repository list
  ansible.builtin.command:
    cmd: helm repo update
  when: inventory_hostname == 'master1'

- name: Install Longhorn Helm chart
  ansible.builtin.command:
    cmd: helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace -f {{ user_home_directory }}/config/longhorn-config.yaml
  when: inventory_hostname == 'master1'

- name: Apply Longhorn UI Service definition
  ansible.builtin.command:
    cmd: kubectl apply -f {{ user_home_directory }}/config/longhorn-values.yaml
  when: inventory_hostname == 'master1'

- name: Patch Longhorn frontend service to LoadBalancer
  ansible.builtin.shell:
    cmd: kubectl patch svc longhorn-frontend -n longhorn-system -p '{"spec": {"type": "LoadBalancer"}}'
  when: inventory_hostname == 'master1'