# Steps to install Metallb
---

- name: Apply MetalLB ConfigMap
  ansible.builtin.shell:
    cmd: kubectl apply -f {{ user_home_directory }}/my-charts/metallb/metallb.yaml
  when: inventory_hostname == 'master1'

- name: Apply MetalLB ConfigMap
  ansible.builtin.shell:
    cmd: kubectl apply -f {{ user_home_directory }}/my-charts/metallb/metallb-config.yaml
  when: inventory_hostname == 'master1'

- name: Pause for 30 seconds to allow Metallb pods to start
  ansible.builtin.pause:
    seconds: 30
  when: inventory_hostname == 'master1'