# Steps to install Longhorn
---

- name: Add Longhorn Helm repository
  community.kubernetes.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
  when: inventory_hostname == 'master1'

- name: Update Helm repository list
  ansible.builtin.command:
    cmd: helm repo update
  when: inventory_hostname == 'master1'

- name: Install Longhorn Helm chart
  ansible.builtin.command:
    cmd: helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace -f {{ user_home_directory }}/my-charts/longhorn/values.yaml
  when: inventory_hostname == 'master1'

- name: Longhorn ingress config
  ansible.builtin.command:
    cmd: kubectl apply -f {{ user_home_directory }}/my-charts/longhorn/homelab.longhorn.yaml
  when: inventory_hostname == 'master1'

- name: Pause for 30 seconds to allow pods to start
  ansible.builtin.pause:
    seconds: 30
  when: inventory_hostname == 'master1'