# Main tasks for RKE2 setup
---
- name: "System requirements Check" 
  ansible.builtin.import_tasks: 00_system_requirements.yml

- name: "Wellcome Message" 
  ansible.builtin.import_tasks: 00_wellcome.yml

- name: "Install RKE2" 
  ansible.builtin.import_tasks: 01_install_rke2.yml

- name: "File Transfer" 
  ansible.builtin.import_tasks: 02_file_transfer.yml

- name: "Install Helm" 
  ansible.builtin.import_tasks: 03_install_helm.yml

