apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-speaker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: metallb-speaker
  template:
    metadata:
      labels:
        app: metallb-speaker
    spec:
      containers:
        - name: speaker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
